### ISSUE TITLE
How to use in VSCode (prettier-vscode)?

### ISSUE THREAD

**Issue by otbe** [sgtpep/prettier-plugin-html-template-literals#1]
Hi,

I tried using this patched prettier version in VSCode, but I wonder if its possible at all?
`prettier-vscode` resolves `prettier` via requiring it, so in the end it will get `index.js` from prettier itself.

Do you know any way to use your patched version in VSCode?

Thanks!

**Comment by sgtpep** [comment]
Hi!

I'm afraid it's not possible to use it within `prettier-vscode` without modifying/forking it. All `require('prettier')` needs to be replaced with `require('prettier-plugin-html-template-literals/prettier')`.

I am not a VSCode user but I hope someone will either publish a modified version of `prettier-vscode`, or collaborate with its author to extend it somehow.

**Comment by otbe** [comment]
There is an open issue to configure the binary path, see https://github.com/prettier/prettier-vscode/issues/232. I think as of now a fork would be the best solution. 
Thanks for you answer. I will close the issue for now.
